src/Event/After.php
src/EventableFilesystem.php

Add $arguments for after event

---

src/MountManager.php
tests/MountManagerTests.php

mount manager decorates the results with a parameter detailing from which filesystem the file belongs to

close #338 mount manager adds reference to the filesystem that listed contents

---

adapter/zip-archive.md

Zip adapter had a paragraph from the ReplicateAdapter

Removed copy-pasted paragraph

---

readme.md

P.S. And fixed a wild space on the Zend Framework integration item

Added CakePHP and Silex integration

---

readme.md

Flysystem Extension for Yii 2: https://github.com/creocoder/yii2-flysystem
Inspired by @GrahamCampbell Laravel integration. Will be updated to Flysystem 1.0.0-alpha1 ASAP.

Added Yii 2 integration

---

api.md

One had a syntax error. The second one was passing a string instead of an array.

Fixed examples

---

phpunit.php
src/Adapter/Local.php
tests/LocalAdapterTests.php

Hey, tried running tests on windows and got some failures. This PR makes all tests pass (or be skipped if impossible) on windows.
What's your policy on windows compatibility? I did not do extensive testing for now, just fixed the test failures.

Windows fixes

---

readme.md

Adding links to adapter repositories. I didn't know that they where in a different repo.

Added reference to adapter repositories

---

caching.md

Just added a word to make it more readable.

Fixed wording on caching page

---

composer.json

I know this is small, but it was annoying me a little.

Make the suggest messages consistent

---

_data/menu.yml
plugins.md

Added documentation for plugins

---

src/Adapter/AbstractFtpAdapter.php

Check if method exists on setting configuration values. Related to https://github.com/helios-ag/FMElfinderBundle/pull/133 and https://github.com/thephpleague/flysystem-sftp/pull/6

Check if method exists on setting configuration values

---

adapter/zip-archive.md

Small typo

---

adapter/dropbox.md

It wasn't clear to me which params to use. So I thought it also might be useful to others to know..

[DX] Clearify usage of Dropbox Client params

---

src/Filesystem.php
tests/FilesystemTests.php

Returns directories/files named "0".

Fixed `listContent()`

---

src/Plugin/PluggableTrait.php

It says "Leave a comment" but I have to words for this :P

Small typo in findPlugin docblock

---

.php_cs

Not actually tested this. Let me know if it's not what you want.

Updated cs rules

---

src/Adapter/Local.php

I decided to make a new member variable, rather than change the existing static $permissions in case subclasses are using that.

Allow defining custom permissions for the Local adapter.

---

README.md

The new Redis Flysystem adapter is now available.  So here's a PR, IAW [Creating an adapter: Sharing the wealth](http://flysystem.thephpleague.com/creating-an-adapter/#sharing-the-wealth).

Add Redis filesystem adapter to README

---

.gitignore
src/Adapter/Ftp.php
tests/FtpTests.php

@frankdejonge here's a PR for the problem mentioned in #554 . Not sure if it's the most elegant way, but I've added some tests and everything is working correctly, so if you have some time go ahead and review  in case you're interested. :smile: 
In the meantime, I'll use my fork for my project. :+1:

Changes in FTP adapter to handle 500 error on some Windows FTP servers.

---

_layouts/default.html

- Anchor tags
--
follow up of #572

Fix base for links in site

---

src/Util/MimeType.php

add svg mime-type

---

README.md

Added a link to the OneDrive adapter in the readme

OneDrive adapter

---

src/Adapter/Ftp.php
tests/FtpTests.php

Credits to #649 by @dominic-horbas 
ftp_systype does not return false on FTP Buffer timeout
This will fix issue #648

isConnected no longer returns true for timeout'd connections

---

src/Adapter/Local.php
tests/LocalAdapterTests.php

Don't set execute permission by default for files.

---

src/Adapter/AbstractFtpAdapter.php
src/Adapter/Ftp.php

Implementation of alternative directory recursion on FTP adapter.

Ftp recursion

---

.gitattributes

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thephpleague/flysystem/679)

export-ignore for appveyor.yml

---

api.md

It hurt my eyes pretty badly when I went through the docs

Fix typo with therefore in API doc

---

api.md

1. Indicate that `deleteDir` deletes directory recursively
2. Add plugin first to use `listPaths()`

Update API docs

---

src/Util/MimeType.php

There are a lot of files with upper or mixed case file extensions.

Make file extension lowercase before mime-guessing

---

adapter/aws-s3-v2.md
adapter/aws-s3-v3.md
adapter/dropbox.md
adapter/rackspace.md
adapter/webdav.md

Unify path prefix docs.

---

src/Adapter/Ftp.php

Check that resource exists before closing in Ftp adapter.

---

src/Adapter/Ftp.php
src/Adapter/Local.php
tests/FtpTests.php

Trying to normalize return values from adapters. Found a bug in FtpTests.php

Make adapter return values consistent.

---

LICENSE

https://www.youtube.com/watch?v=-b3XTj5G_SA

Whats another year?

---

README.md

Add the missing link for "Azure Blob Storage" adapter. Thank you!

Add Azure Blob Storage link

---

README.md

AliYun OSS Storage adapter for flysystem
Project Url
https://github.com/xxtime/flysystem-aliyun-oss

add aliyun oss adapter

---

src/Filesystem.php

Mini inconsistency fix

---

README.md

Citrix ShareFile added to the list of community supported adapters and sorted the list alphabetically

Citrix ShareFile added to the list of adapters

---

src/Adapter/Ftp.php
tests/FtpTests.php

This should fix #817. We should add a test but it won't be fun.

Delete all files first so directories are empty in FTP Adapter.

---

src/Adapter/Local.php

#904: Don't set null values for local adapter.

---

docs/adapter/digitalocean-spaces.md

For those who are unfamiliar with AWS S3 it is unclear how to use `flysystem-aws-s3-v3` adapter with Digital Ocean Spaces: https://github.com/thephpleague/flysystem-aws-s3-v3/issues/127

Add example for Digital Ocean Spaces

---

docs/adapter/digitalocean-spaces.md

Fix PHP code formatting here: http://flysystem.thephpleague.com/adapter/digitalocean-spaces/

Add missed tags for digitalocean-spaces.md

---

docs/adapter/phpcr.md

And sort other imports alphabetically

Properly import PHPCR\SimpleCredentials

---

src/MountManager.php

As discussed in https://github.com/thephpleague/flysystem/issues/918

int|false as return type in PHPDoc for getTimestamp()

---

docs/adapter/phpcr.md

Also see https://github.com/phpcr/phpcr/pull/101#issuecomment-391240015

Indicate that Credentials are optional during login

---

README.md

It's a pure PDO adapter I created some time ago. Storing files in database is usually not the best idea, but on the other hand I saw many projects where it was a requirement. Maybe someone will find it useful.

Added PDO database adapter to Community Supported adapter list

---

docs/guides/deterministic-programming.md

Very minor typo but I saw it.

---

src/MountManager.php
stub/FilesystemSpy.php
tests/MountManagerTests.php

Make MountManager implement the FilesystemInterface

---

docs/adapter/sftp.md

SFTP usually uses port 22

---

docs/usage/filesystem-api.md

Just some variable name inconsistencies and I believe an incorrect return type.

Fixed some inconsistencies in API docs

---

README.md

Nette framework is probably unknown for you, but it is dominating framework for us in Czechia and Slovakia. So it may help some Nette users which would find that.

Add note about Nette integration

---

src/Adapter/Local.php

Inspired by https://github.com/thephpleague/flysystem/pull/982

Cache clear added to avoid potential issues with concurrent processes

---

docs/_data/menu.yml
docs/adapter/google-cloud-storage.md

Adds a page for Google Cloud Storage (GCS) adapter to https://flysystem.thephpleague.com/docs/

Adds Google Cloud Storage to Flysystem website

---

README.md

Documentation update for SSH/Shell adapter. It only requires ssh and few basic unix commands.

Documentation update for SSH/Shell adapter

---

.gitignore
.travis.yml
composer.json
phpstan.php
src/Config.php

* Updated phpstan to version 0.11.8
* Bumped phpstan level to 5
* Fixed clearstatcache location being used as 1st parameter instead
as 2nd parameter
* Fixed config fallback incorrect phpdoc

PHPStan level 5 + upgrade to 0.11.8

---

changelog.md

Somehow the changelog here does not mention 1.0.54
I think this is what is needed to correct it.

Fix changelog order and put 1.0.54

---

README.md

As per twitter messages between Frank and Guus

Added flysystem-raid to Community Supported Adapters list

---

docs/adapter/aws-s3-v3.md
docs/adapter/gitlab.md
docs/adapter/phpcr.md
docs/advanced/caching.md
docs/advanced/upgrade-to-1.0.0.md
docs/guides/uploads.md
docs/index.md
docs/usage/filesystem-api.md

Refer to #1073 
I hope not meaningless PR :smiley:

Improve docs

---

README.md
docs/adapter/gitlab.md

Thank @carusogabriel for finding it :smiley:

Replace Gitlab with GitLab

---

src/Util/MimeType.php

Noticed that dotm is missing in the list. Added this one.

Added dotm mime type

---

src/Util.php

https://www.php.net/manual/en/function.empty.php#103756

Allowed some empty dirname in emulateObjectDirectories() method

---

README.md

add a new community support
