thephpleague/flysystem

src/Util.php

If folders are created using AWS console in an S3 bucket, they will have their own listing there and will appear in the original $listing array. This patch ensures that the folders are not listed twice, if that is the case.

Prevent duplicate listing of directories.

---

adapter/aws-s3-v2.md

Adapter can't be found in example.

Namespace Typo

---

adapter/webdav.md

Wrong casing for namespace and classname in the doc.

Fix casing for flysystem webdav adapter

---

.travis.yml
composer.json

* Use `composer update` to test against the highest dependencies
* Also test against the lowest supported dependencies
* Added testing on the upcoming php release (7.0)
* Use [container-based](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) travis builds 
* Removed `bash -c` calls that aren't required on Travis
Doing this uncovered an [issue](https://travis-ci.org/duncan3dc/flysystem/builds/52409522) in the dependencies, where it was stated the phpunit 4.0 was required, when actually 4.1 is required. so I've bumped that requirement in `composer.json`

A bunch of stuff for Travis CI

---

src/Adapter/Ftp.php

After the ltrim on the directory listings on 287, directories with a dot prefix will not match on 290. This causes the FTP adapter to try and create a directory that already exists which results in an error.

Fixes an issue uploading 'dot prefixed' directories with the FTP adapter

---

src/Util.php

Fixes a bug where any two digit filename causes an error. (In our case, the filename was the ID of the file in our database e.g. "35")

Fixing nonescaped regex chars

---

src/Util.php
tests/UtilTests.php

The current regex that handles the removal of self referring parts in the path doesn't seem to work properly in some cases:
Examples:
```php
$path = Util::normalizePath("dirname./");
// Expected:    
$path == "dirname.";
// Actual:           
$path == "dirname";
$path = Util::normalizePath("dirname/.");
// Expected:    
$path == "dirname";
// Actual:          
$path == "dirname/.";
$path = Util::normalizePath("dirname/../");
// Expected:    
$path == "";
// Actual:          
$path == "dirname/.";
```
With this change the regex will replace "." at the end of the path only if it's after a "/ " and it's followed by either a "/" or the end of the string

Changes in the way some paths are normalized

---

composer.json

```Util::contentSize``` makes use of an mb_* function so this library should depend on it.

Require ext-mbstring in composer

---

src/Adapter/Local.php

In function deleteDir(), a file of type 'link' couldn't be deleted.
In function normalizeFileInfo(), the $file->getMTime() call throw a RuntimeException when called on a non resolvable symbolic link.

Fix two bugs with file of type 'link'

---

src/Adapter/Local.php

Use the same chmod (777) in both, and write the is_dir() check the same way other methods use it.
Also, reset umask to 0 to make mkdir() reliable.

Consistency between ensureDirectory() and createDir()

---

adapter/aws-s3-v2.md
adapter/aws-s3-v3.md
adapter/azure.md
adapter/ftp.md
adapter/gridfs.md
adapter/local.md
adapter/null-test.md
adapter/phpcr.md
adapter/rackspace.md
adapter/sftp.md
caching.md
integrations.md
mount-manager.md
recipes.md
upgrade-to-1.0.0.md

Cleaned up the docs a bit after reading through them earlier today. Just some small things.
- Added the same titles to all the different adapter docs
- Converted arrays to short syntax (since Flysystem requires PHP >=5.4)
- Fixed some titles
- Removed the `<?php` opening tag from all code blocks except for the two where you were displaying an entire file
- Added some missing code for 2 recipes
- Tweaked 2 lists with links (this was a personal choice, I can always change it back if you want)
One suggestion: I'd add links to the main docs in each adapter's readme instead of keeping install/usage notes in both main docs and each readme. Things can get outdated real fast currently.
Hope you like :)

Cleanup documentation

---

src/Filesystem.php

I am working on a saas platform in Symfony that has adapters (credentials, buckets etc) per client. They do share the filesystems (profile pictures, page file and image uploads etc). However the OneUp FlysystemBundle only allows adapter configuration through the symfony config file.
My plan was to fork that bundle, add an adapter registry, inherit the filesystem class, override its constructor method to take the registry and the adapter name to look up instead of the concrete adapter. Finally with this pull request I only have to override the getAdapter method to add the lookup in the registry, a null check and a nice exception to it.
When all the methods use the internal property this requires me to inherit but also copy paste the whole class to make the required changes.

Change adapter variable lookups to property calls, allow better extending of filesystem class

---

src/Adapter/Ftp.php
tests/FtpTests.php

When calling Ftp::getMetadata() on a directory, it returns the metadata for the first file in the directory.
This doesn't really gather any metadata at this point, my thought was once we determined the path is a directory, we could call ftp_rawlist() on the parent directory to actually gather metadata.
Starting with this to see if it's a reasonable idea, or if I'm just completely wrong.

Allow Ftp::getMetadata() to work for directories.

---

src/Filesystem.php
src/FilesystemInterface.php

This moves all of of the docs back into FilesystemInterface from Filesystem where appropriate. It also fixes a bunch of docs that were just wrong, or copy-pasted incorrectly. Lastly, it documents all of the exceptions thrown at the moment.

Doc string fixes.

---

adapter/zip-archive.md

Added a section which explains how you can force a newly created zip to be saved before the end of a PHP request.

Add force save section to ZipArchive adapter docs

---

src/Adapter/Local.php
tests/LocalAdapterTests.php

In the Local adapter, we're doing fwrite(fread(..., 1024), 1024). This should use stream_copy_to_stream(). Is there a reason that it's not currently doing this?

Use stream_copy_to_stream().

---

.scrutinizer.yml

Scrutinizer keeps failing my pull requests. Let's increase the timeout.
I guess we'll see if this is long enough :).

Increase scrutinizer timeout.

---

src/Filesystem.php
tests/FilesystemTests.php

`Filesystem::put()` and `Filesystem::putStream()` both call `Filesystem::has()` and then the appropriate `write()` or `update()` call. This duplicates calls to `has()` in the `assertPresent()` or `assertAbsent()` calls. For a minor amount of code duplication, we can save a whole round trip to the filesystem.

Optimize put() and putStream() to call has() only once.

---

src/Adapter/Ftp.php
tests/FtpTests.php

The patch should be self explanatory. The test case illustrates the problem. I'm not sure if the test case is necessary, but there it is.

Don't use empty() to check directory length in Ftp adapter.

---

src/Adapter/Ftp.php
src/Adapter/NullAdapter.php
tests/UtilMimeTests.php

A few things are happening here.
- The return value of fclose() in Ftp::write() shouldn't affect the return value of the call. Even if we can't close our temp file, the write was still successful.
- I changed tmpfil() to a temp stream, since that will keep up to 2MB in memory, and the $contents is already in memory anyway.
- Removed the setVisibility() call in write() since writeStream() calls it anyway. No need to make the request twice.
- Removed some stray calls to Util::ensureConfig() that aren't necessary since the type hint doesn't accept null. I did a quick search, and found one in NullAdapter as well.
- Moved the mime-type guessing to the end, no reason to do it if the call fails.
If you think any of these are wrong, or should be done in a follow up, let me know and I'll gladly …

Don't depend on fclose() of temp stream for return value to write() in Ftp adapter.

---

src/Adapter/AbstractFtpAdapter.php
src/Adapter/Ftp.php
src/NotSupportedException.php
tests/FtpTests.php

This is an attempt at support for Windows FTP systems, by trying multiple parsers. (See #451)
- First try to parse as Unix
- If fails, parse as Windows
- If fails, empty array (or in future, more parsers)
This modifies the Unix (current) parser by adding a check to see if the format is as expected, to prevent an exception.
Windows parser is a modified version, based on the one from @kinncj in the mentioned PR. This adds support for short+long date format. 
I've added tests for the windows lines, which only proves that it doesn't throw an exception (like before), but should probably check the desired output also.
Haven't actually tested this on a 'live' Windows server, so could use some testing.
/cc @kinncj @frederikbosch @jelrikvh @JLeitchSCO

[FTP] Support windows

---

src/Adapter/Local.php

For a project we encountered a problem with the local adapter, our mounted storage (nfs share) didn't support exclusive locking. 
In the pull request you can set the flags for the file_put_contents in the config.

Added config for file_put_contents flags

---

composer.json
src/Util.php

Sorry to be inundating you with pull requests. Thanks for taking them!
As far as I can tell, the only reason there's a dependency on mbstring is because of the mb_strlen($contents, '8bit') call in Util.
I would prefer just documenting that 'mbstring.func_overload' is unsupported, as it's only for legacy apps, but this would work and be backwards compatible.
Are there other adapters that require mbstring?
We could cache the results of ini_get() as well, but that might be overkill.

Remove dependency on mbstring.

---

changelog.md
src/Handler.php
tests/HandlerTests.php

This is an absolute must for any project approaching complex!
Here's one particular issue I ran into: https://github.com/anomalylabs/files-module/blob/master/src/Adapter/AdapterFilesystem.php#L193
That class wraps the Filesystem class ONLY to keep a database in sync. The disk MUST be set on the Filesystem because there are different disks (Laravel disks) using different adapters and I need to know if file1 is on disk A or B for instance when I sync. 
The problem here is that now that I have a hard dependency on the disk (in construct) I have a hard dependency on the Filesystem. And when copying or moving from the mount manager - there very well may be a different source Filesystem. Sure, I could resolve it from the path, but it makes a ton more sense having it on the Handle. OOP FTW! …

Allow retrieving the Filesystem from the Handler.

---

src/Adapter/Local.php
tests/LocalAdapterTests.php

Closes #522.
This implements the permissions `0755` (public) and `0700` (private) for directories in contrast to `0744` and `0700` for files. Previously, files and directories were treated the same but `0744` is useless for directories.
Also, this sets `0755` instead of the insecure `0777` as default permissions for all newly created directories (including the root directory).

Distinguish between file and directory permissions in the local adapter

---

src/Adapter/Local.php
src/Filesystem.php
tests/FilesystemTests.php

I imagine this issue is getting pretty old, my apologies.
First off, checking for the Local adapter in Filesystem is not nice. The part of this patch that changes that needs to be discussed. I'm replacing back slashes with forward slashes. This is not technically correct, since Linux file names can have backslashes in them, but at some point we're going to have to decide what a valid file path can be. I had actually assumed that `Util::normalizePath()` already did this.
Other bugs fixed:
- Treating the int 0 as a string. (This is debatable, but I think a zero int is much closer to false than a string) This also avoids calling strlen() on every path.
- When a sub-directory matches. I.e. listContents('dir') returns 'a/dir/file.
- Fixed test coverage. The big || list was hiding missing test …

Fix listContents().

---

src/Adapter/Local.php

When implementing a cleanup method I noticed that directories that linked to external resources where not cleared by `Local::deleteDir()` method. This commit fixes that particular problem (target directories are not deleted, only links are removed).

Unlink links to directories

---

src/Util.php

Even though the PHP documentation states that `pathinfo()` will always
return an associative array with certain keys, for certain values
`pathinfo()` returns a sparser array.
E.g. `pathinfo(false)` and `pathinfo('')` return an array with only
'basename' and 'filename' keys on php 5.6.12 and php 5.5.9, possibly
others.

Fix Util::pathinfo assuming dirname always exists

---

.gitattributes

`.gitattributes` is case sensitive, so `readme.md` does not work, the file is still included with a `composer install`.

Change readme.md to README.md in .gitattributes

---

core-concepts.md

- Links to anchor tags
--
On this page, the links to the anchor tags are broken: http://flysystem.thephpleague.com/core-concepts/

Fixed links to anchor tags

---

README.md

The linked adapter has'nt a high testing coverage yet, but it's in progress. The idea of the adapter is to use the main adapter whenever is possible, and only using the fallback adapter when it's impossible to find a file using the main one.

Added link to Litipk's Fallback adapter

---

src/Adapter/Ftp.php

If `$this->connection` has failed and is a boolean, calling `ftp_systype($this->connection)` throws a PHP warning (Warning: ftp_systype() expects parameter 1 to be resource, boolean given). I propose first checking to see if `$this->connection` is a resource or a boolean/null and if it's going to fail anyway, to start the failure sooner.

Check For Failed FTP Connection to Avoid PHP Warning

---

composer.json
tests/FilesystemTests.php
tests/GetWithMetadataTests.php
tests/HandlerTests.php
tests/ListFilesTests.php
tests/ListPathsTests.php
tests/ListWithTests.php

Prophecy test cases are supported by PHPUnit since version 4.5.
So phpspec/prophecy-phpunit is deprecated and unneeded.
Also allow PHPUnit 5 (tested with PHPUnit 5.1.4, PHP 5.6.17 and 7.0.2)

drop dep on deprecated prophecy-phpunit

---

src/Adapter/Ftp.php

In function createActualDirectory ( class FTP ) in FTP.php file is bug. There is a listing of directories with php function ftp_nlist and after that we iterate them. But when ftp_nlist goes to directory that it need to be created recursively it returning false and for-each statement is falling.

Ftp Adapter bug fix

---

src/Adapter/NullAdapter.php

There is no variable size so compact can't return it

remove size from write method in null adapter

---

src/Adapter/Ftp.php
tests/FtpTests.php

Hi!
With adapter for FTP, when you list a directory, it will return hidden files correctly. But when you try check if exists (with has method) or get its content or, definitely, you use a method that uses the method getMetadata then doesn't work.
This resolves #601

Fix getMetadata in FTP adapter for hidden files in unix systems

---

src/Util.php
tests/UtilTests.php

This fixes the mime type guessing [issue](https://github.com/thephpleague/flysystem/issues/607). Apparently Finfo cannot be trusted.

Quick and dirty fix for Util::guessMimeType(). Fixed #607

---

README.md

We needed to have both AWS V3 and Google Storage adapters in place simultaneously, so the V2 driver was not an option as a work-around. - see https://github.com/thephpleague/flysystem/issues/448

add link to google cloud storage adapter in readme

---

README.md

Gaufrette recently added a flysystem adapter (https://github.com/KnpLabs/Gaufrette/pull/390) so I've created an adapter going in the other direction to simply reciprocate the love (plus I think it can be useful). 
https://github.com/jenkoian/flysystem-gaufrette

Add Gaufrette Adapter to list of Adapters

---

README.md

As per https://techlib.barracuda.com/CudaDrive/EOL, the Copy/Cuda drive service is dead. Remove it from the list of adapters.

Remove copy.com from adapter list.

---

src/Adapter/Ftp.php
tests/FtpTests.php

Some FTP return "total 0" line as the first item of the `ftp_rawlist`. If this is the case the array is shifted so the actual line is used
As one can see in this picture from a client's FTP:
Otherwise the following error is thrown:
`PHP error:  Undefined offset: 8 in myrepo/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php on line 398`
This is related to [#229](https://github.com/thephpleague/flysystem/issues/229)

Bugfix "Undefined offset: 8" in some unix FTPs

---

src/Adapter/AbstractFtpAdapter.php
tests/FtpTests.php

Related to [#613](https://github.com/thephpleague/flysystem/pull/613) and [#229](https://github.com/thephpleague/flysystem/issues/229).
Throwing a descriptive error instead of `PHP error: Undefined offset: 8`.
I'm not sure a `RuntimeException` is the specific type that should be thrown (?)

Throw descriptive error when an invalid listing object is found

---

README.md

The elFinder flysystem driver makes it possible to browse/upload/download to all Flysystem adapters.
For a demo, see http://studio-42.github.io/elFinder/ (which has a Google drive example)

Add elFinder integration

---

src/MountManager.php
tests/MountManagerTests.php

Allows options such as AWS visibility or mimetype, to be used with MountManager move and copy.

Added missing config parameter to move and copy, to allow passing through of options.

---

src/Adapter/Local.php
tests/LocalAdapterTests.php

To fix a weird use case. Imagine the root directory is `/foo/bar/baz`
At the creation of the Local adapter, everything's OK. The root directory `/foo/bar/baz` is created.
Then the directory `/foo/bar` is deleted and the permissions on `/foo` are changed. No possibility to read/write anymore in this directory.
Then every call to the read/write methods of the adapter will "fail" silently.

Fix root directory creation problem

---

src/MountManager.php
tests/MountManagerTests.php

See https://github.com/thephpleague/flysystem/issues/650

Fixed #650 - MountManager::filterPrefix only fixes the first path

---

src/Filesystem.php
src/Plugin/ForcedCopy.php
src/Plugin/ForcedRename.php
tests/ForcedCopyPluginTests.php
tests/ForcedRenamePluginTests.php

RE: #292 
Trying to extend the interface, or default implementation, leads to problems.
Here's an implementation via plugins.

Implement copy and rename plugins that overwrite destination.

---

src/Adapter/AbstractFtpAdapter.php
tests/FtpTests.php

Currently, if the date/time doesn't match either of the 2 formats. DateTime will return false and ->getTimestamp() causes an exception `Call ->getTimestamp() on boolean`.
I order to prevent this exception. I've made a check that will first check if DateTime is not false and if it is, it will try to create a timestamp using `strtotime`.
The value from `strtotime` is cast to an int so if that also returns false, it will return 0 (which is a valid timestamp).

Make the windows date/time normalizer not cause an exception if the date could not be parsed

---

src/Adapter/Ftp.php
src/Adapter/Local.php

See http://php.net/manual/en/function.fopen.php and https://github.com/thephpleague/flysystem/issues/72#issuecomment-233303480
> For portability, it is strongly recommended that you always use the 'b' flag when opening files with fopen().

Read stream in binary mode

---

src/Filesystem.php
src/MountManager.php

`MountManager` and `Filesystem` classes had missing return type declarations for `assert*` methods. This prevents using these classes when you're doing `phpspec`. An exception is thrown stating these methods are not existing.
In short, `phpspec/prophecy` relies on `phpdocumentor`, where an empty type declaration causes an exception to be thrown (`'Attempted to resolve "' . $type . '" but it appears to be empty'`) during parsing the class docblock. This will prevent phpspec to get a list of any of the supported magic methods.

Add missing return type declarations

---

README.md

Hey,
I've written an adapter for OpenStack Swift. It uses php-opencloud/openstack as a base as rackspace/php-opencloud is going to enter end-of-life soon.
Hope this is useful for some people.

Adding OpenStack Swift adapter to readme

---

src/Config.php

Currently `League\Flysystem\Config::has()` doesn't check if the `$key` exists on the fallback config. 
I was testing the [`Superbalist/flysystem-google-cloud-storage`](https://github.com/Superbalist/flysystem-google-cloud-storage) and it [relies on the previously mentioned method](https://github.com/Superbalist/flysystem-google-cloud-storage/blob/master/src/GoogleStorageAdapter.php#L142) to check if the `visibility` was set but it would never return true, so after some debugging this is my finding and suggested fix.

fix League\Flysystem\Config::has() so that it also checks the fallback config

---

src/Adapter/Local.php
tests/LocalAdapterTests.php

FIX: no need to use realpath($root) in Local adapter for ensureDirectory method - directory already ensured by is_dir($root) (realpath function causes issues when running script without executable permissions on all directories in the hierarchy)

Fixed ensureDirectory method in Local adapter - Dir seems to be not readable although it is

---

src/Util.php
tests/UtilTests.php

Bug example:
echo Utils::normalizeRelativePath('example/path/..txt'); 
//Output: example/txt
//Expected: example/path/..txt
Because after .. must be / or end of string.

Fix Util::normalizeRelativePath

---

src/Adapter/AbstractAdapter.php
src/Adapter/Local.php
tests/LocalAdapterTests.php

Relating to #739 and #740.
I was doing some investigating, and I couldn't find a problem.
I wonder @ArminVieweg, are you using the  Local adapter directly?
Anyway, while I was digging in, I added some tests, and found some ways to simplify the logic surrounding path prefixes.

Simplify prefix handling.

---

src/Util.php
tests/UtilTests.php

Issues:
1. Just because a path contains a backslash, doesn't mean it's a Windows path. Backslashes are valid in file/directory names on Linux.
2. Windows is fine using forward slashes for paths.
3. The regex was hard to figure out. This, to me at least, is a lot simpler to follow.
4. Added a test to check about removing null bytes.
Even though Linux supports backslashes, I haven't checked all the other adapters to see what they support. And, since backslashes are directory separators on Windows, we could wind up with different file structures if we allowed them. This seems like the lowest common denominator.
Also, I've merged `normalizePath()` and `normalizeRelativePath()` since I don't see a safe subset for `normalizeRelativePath()` to do, or how they are really different.

Fix Windows path handling and simplify path normalization.

---

src/Util/MimeType.php

Multiple instances of failed composer installs when Finfo::buffer
throws ErrorException resulting in logs of Array to String Conversion.
Simple catch to return null

Array To String Conversion throw when ErrorException

---

src/Adapter/Ftp.php

Right now, you cannot create a folder named "01" if already a folder named "1" exists because the check for existing directories is not strict enough.

Use strict comparison because folder "01" is not equal "1" for example.

---

src/FilesystemInterface.php

When using the FilesystemInterface it is assumed that the
InvalidArgumentException is in the same namespaces as the Interface, due
to a missing backslash.

Add correct namespace for InvalidArgumentException

---

src/Adapter/Ftp.php

Bug example:
```
$filesystem->has('that path/have/the space character.txt');
// Return false every time if in path have space character.
```
Because before call ftp_rawlist we need add a slash in front of each space character in path.
```
$options = '-A';
$path = str_replace(' ', '\ ', $path);
$result = ftp_rawlist($connection, $options . ' ' . $path);
```

Fix: escape space characters for ftp adapter

---

adapter/dropbox.md

The current Dropbox adapter uses v1 of their API. That version has been deprecated and will be switched off on Juni 2, 2017.
More info on that here: https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/
This PR replaces the old adapter with a newer one that is built on v2 of the Dropbox API.

Suggest a Dropbox adapter that uses v2 of the Dropbox API

---

src/Adapter/Ftp.php

The first call of the ftpRawList was not escaped, because getConnection() must be called before checking on the Pure-Ftpd Server.

Fix the ftpRawList path escape

---

src/Adapter/AbstractFtpAdapter.php

**Example issue**
```
$permissions = normailzePermissions('-rwxr--r--');
printf("%o\n", $permissions);  // 17, but expected 744
```
And because of this, the `getMetadata` will always return an array with a public visibility.
That PR fix it.

fixed the normalizePermissions

---

src/MountManager.php

When moving a file using the MountManager, if from and to are in the same file system, perform a rename instead of copying and deleting the file.

Rename when moving file within the same file system

---

src/Filesystem.php

Hello,
I am proposing to check for existence of the `timestamp` key in the returned file info array instead of the key `mimetype`, which apparently was a result of copy-pasting the implementation for `getMimetype()`.
If this was intentional -- sorry!
Thanks

getTimestamp() in Filesystem

---

src/Util.php
tests/UtilTests.php

As mentioned in #235, `pathinfo()` has inconsistent handling of UTF-8 file paths.
This has been a known problem for quite some time, and I'm surprised it's taken this long to get reported.
I know that Drupal implements their own version of `basename()` for this reason.
See http://bugs.php.net/bug.php?id=37738
This is a clean-room implementation of the required methods.

Implement custom pathinfo() functions.

---

composer.json

If PHP has been built without these extensions then the FtpAdapter won't work

Suggest extensions needed for standard FTP

---

docs/adapter/aws-s3-v3.md

The existing example references actions that do not exist. See http://awspolicygen.s3.amazonaws.com/policygen.html

Fix invalid S3 Policy Example.

---

docs/adapter/azure.md

The root namespace was changed in microsoft/azure-storage:0.10.0 according to their [Changelog](https://github.com/Azure/azure-storage-php/blob/master/ChangeLog.md):
Change root namespace from "WindowsAzure" to "MicrosoftAzure/Storage"

Updated ServicesBuilder class name

---

docs/performance.md

Correct 'new' to 'use' when importing namespaces

---

docs/caching.md

I found the documentation a bit confusing due to the same aliases used in all examples. Hope this clears it a bit up.

Use aliases in documentation

---

src/Adapter/AbstractAdapter.php
src/Adapter/Ftp.php
src/File.php
src/Plugin/EmptyDir.php
src/Plugin/ListWith.php
src/Util/ContentListingFormatter.php
src/Util/MimeType.php
src/Util/StreamHasher.php

* $root in Ftp::setConnectionRoot is always defined, but sometimes it doesn't have value. Check $root instead of isset($root)
* Fixed many phpdoc errors.
* Correct case for finfo instead of Finfo
I found these errors thanks to phpstan static analysis tool. phpstan can be executed with following script:
``` sh
ls phpstan.phar || wget https://raw.githubusercontent.com/phpstan/phpstan-shim/0.9.1/phpstan.phar && \
chmod 777 phpstan.phar && \
./phpstan.phar analyse -a vendor/autoload.php -l 7 src
```

Fixed phpdoc and in FTP check root content instead of isset

---

src/Adapter/Ftp.php

The `isConnected()` function always lists the root directory of the ftp server to determine if the connection is active. 
This changes that to list the root of the adapter instead. It's useful for when you have a very large root directory causing LIST commands to take a long time and you want to specify a sub-directory as root to speed things up.

Improve isConnected()

---

src/Adapter/Ftp.php
tests/FtpTests.php

FTP listings must be normalized by prepending the base directory to all paths.
Automatic recursion mode already does that (note the `$directory` parameter): https://github.com/thephpleague/flysystem/blob/3b7394d78ad5936dab8a7041c63ac83722af27d9/src/Adapter/Ftp.php#L500

FTP: Fix manual recursion mode

---

.gitattributes

Docs are not needed for composer installs.
Also I'm not sure why `wait_for_ftp_service.php` is shipped.

Don't ship docs with composer installs

---

src/ReadInterface.php

Since the original description of the getTimestamp method did not describe that the method returns the last modified time of the file, replace the description to make it clear that the getTimestamp method returns the last modified time of the file as a timestamp.
Closes thephpleague/flysystem#836

Replace the description of the getTimestamp method

---

docs/index.md

I've added some Getting Started links to the main content area of the Docs page.
This should help people who land on that page have a clear idea of what to do next as they're learning Flysystem.

Add some "Getting Started" links

---

docs/api.md

According to the php documentation %G is not the year you might expect but can in some years be the year number from the previous year.

Fix strftime in api doc

---

src/Adapter/Local.php
tests/LocalAdapterTests.php

A PHP Warning is thrown if the file to delete is missing, this can be due to a race condition.
This fix suppresses the warning allowing unlink to return true/false as expected.

Suppressed Warnings on unlink and added tests to support change.

---

src/MountManager.php

FilesystemInterface::writeStream can throw a FileExistsException, as a result MountManager::copy throws it as well

Added FileExistsException to MountManager::copy annotations

---

README.md

Hi,
I've made an adaptation of flysystem-google-drive adapter which allows you to use regular paths instead of paths built from unique identifiers. All ID handling is performed in the adapter (also with heavy built-in caching).
For example:
"native google drive path" **/Xa3X9GlR6EmbnY1RLVTk5VUtOVkk/0B3X9GlR6EmbnY1RLVTk5VUtOVkk** 
becomes **/My Nice Dir/myFile.ext**
I also included a fix for Google_Http_MediaFileUpload which reduces memory usage by using Psr7 streams and sends everything in chunks instead of loading the whole file in memory before sending.
This PR request adds a link to the new Google Drive adapter.

Updated README.md with link to new Google Drive adapter

---

src/Adapter/Local.php

That would be great to be able to get the error message with exact reason why the directory was not created.
Also the result of `is_dir` function is cached. So if directory was created by another php process, then it still will return `false`. So the cache should be cleared before the second `is_dir` call

Local::ensureDirectory - improve error message; clearstatcache

---

src/Util/MimeType.php

When retrieving files with the .rdf extension we get `text/plain` as a ContentType. We would however expect to see `application/rdf+xml` set as a ContentType.
This pull request adds the rdf extension to the mimetype util, and resolves this issue.

Added RDF extension to mimetype util

---

docs/_data/menu.yml
docs/adapter/scaleway-object-storage.md

Hello,
Would it be possible to add [Scaleway Object Storage](https://www.scaleway.com/object-storage/) to the list of adapters?
Their API is S3 compliant. I also verified that it works.

Added Scaleway Object Storage to list of adapters

---

docs/usage/filesystem-api.md

the Create Directories has some typo of the description and type for $response.
change it same to Delete Directories

fix some typo in docs about `Create Directories`

---

docs/adapter/aws-s3-v3.md

S3Client::factory is deprecated and this is the right way to instantiate
the class.
I'm not sure about how this works in the v2 library so I left it alone.

[DOC] Update S3Client invocation

---

README.md

add alternative pdo adapter link: [phlib/flysystem-pdo](https://github.com/phlib/flysystem-pdo)
i've been using this adapter one since Sep 6,2017:
- https://github.com/eventum/eventum/pull/254#event-1235986681

readme: add phlib/flysystem-pdo link

---

changelog.md
src/Adapter/AbstractFtpAdapter.php
src/Adapter/Ftp.php
tests/FtpTests.php

I've been using the 'timestamp' property to sort/filter files on local and ftp filesystems.
Calls to listContents depending on the 'timestamp' property had been working on some FTP servers and crashing on others (due to missing 'timestamp'), discovered it was due to 'windows' listings returning timestamps, but 'unix' listings not.
This patch provides returning a best-effort (given the limitations of the 'LIST' command) listContents timestamp for FTP servers using 'unix' style listings.

Ftp::listContents support for 'timestamp' attribute

---

docs/usage/filesystem-api.md

I noticed there is a missing equals sign in the docs.

Added missing equal sign in documentation

---

src/Util/MimeType.php

In order to comply with the last RFC (https://tools.ietf.org/html/rfc7111)
referring to the MIME type of the CSV files these should be of the text/csv type.

Update the MIME type of CSV files.

---

README.md

The `README.md` at https://github.com/heybigname/backup-manager suggest the repo should no longer be used, and users are redirected to https://github.com/backup-manager.

Updated backup-manager Github URL

---

docs/adapter/ftp.md

The option `ignorePassiveAddress` of the FTP adapter is missing in the documentation. I don't know if `false` should be the documented value though 🤔 !

Add `ignorePassiveAddress` option to docs

---

docs/_data/menu.yml
docs/adapter/gitlab.md

I created a Gitlab Storage Adapter implementing Gitlab's Repository v4 REST API.
Hereby I would like to request to add this adapter to the documentation.

Gitlab Repository API Adapter

---

src/Adapter/Ftp.php
src/Adapter/Local.php

Right now in our API calling the guessMimeType method is causing out of memory exceptions because it loads the entire file into a buffer. 
See `return $finfo->buffer($content) ?: null;` in `MimeType.php`

Don't guess mimeType when it's known

---

src/Adapter/Local.php
tests/LocalAdapterTests.php

I will outline the main problems in a codeblock:
```php
mkdir($this->root.'subdir', 0750);
$output = $this->adapter->getVisibility('subdir');  
// wrong response - returns public, but public is 0755 by default
$permissions = [
'dir' => [
'yolo' => 0777,
'private' => 0770,  // private to me and the gang
],
];
$adapter = new Local($this->root, LOCK_EX, Local::DISALLOW_LINKS, $permissions);
$adapter->createDir('private-dir', new Config());
$adapter->setVisibility('private-dir', 'private');
$output = $adapter->getVisibility('private-dir');  
// wrong response - returns public not private
$adapter->createDir('yolo-dir', new Config());
$adapter->setVisibility('yolo-dir', 'yolo');
$output = $adapter->getVisibility('yolo-dir');
// wrong response - returns public not yolo
```
I've added tests that …

Fixed Local::getVisibility not working correctly with customised visibilities

---

changelog.md
src/Adapter/Ftpd.php
tests/FtpTests.php
tests/FtpdTests.php

Follows the parent class fix 5901bb55
Before the change, calling getMetadata() over an existing directory produced a fatal error.
```
PHP Fatal error:  Uncaught RuntimeException: Metadata can't be parsed from item 'total 334920' , not enough parts. in /app/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php:435
```
Ftpd produces the following output on `STAT` call over directory:
```
array(46) {
[0]=>
string(32) "212- Status of content10/export:"
[1]=>
string(12) "total 334920"
[2]=>
string(72) "-rw-r--r--  1 1000  1000   3645884 Jul 18 06:10 movie.ts"
[....]
[45]=>
string(18) "212 End of status."
}
```
Then, it can not be parsed by `normalizeObject`

Fixed listing of the existing directory in Ftpd

---

docs/adapter/aws-s3-v3.md

It is actually `endpoint` that should be used
See https://github.com/aws/aws-sdk-php/blob/0326ba62f6ee0bb075f2b875631ec4abee93bee1/src/AwsClient.php#L107-L109

Fix config parameter name for S3.

---

docs/guides/deterministic-programming.md

"Disc" (with a C) is used for audio records, CDs and the like, whereas a computer hard-drive is a "disk" (with a K)

Correct "disc" to "disk"

---

docs/usage/filesystem-api.md

I've added the optional `$config` parameter where allowed using the square brackets (like PHP.net does) to indicate it isn't mandatory. Also I've added the `false` as a union type when ever a `string` content is returned or false in case of failure.

Describe optional config param and possible false return in case of failure

---

src/Adapter/Local.php

With PHP 7.4.0RC3
```
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.4.0RC3
Configuration: /dev/shm/BUILD/flysystem-33c91155537c6dc899eacdc54a13ac6303f156e6/phpunit.xml
...............................................................  63 / 354 ( 17%)
............................................................... 126 / 354 ( 35%)
............................................................... 189 / 354 ( 53%)
..........F...R................................................ 252 / 354 ( 71%)
............................................................... 315 / 354 ( 88%)
.......................................                         354 / 354 (100%)
Time: 185 ms, Memory: 14.00MB
There was 1 failure:
1) League\Flysystem\Adapter\LocalAdapterTests::testMimetypeFallba …
```

add 'application/x-empty' for 7.4

---

src/Util/MimeType.php

According to https://blogs.msdn.microsoft.com/vsofficedeveloper/2008/05/08/office-2007-file-format-mime-types-for-http-content-streaming-2/ the correct mime type for dotx is   `application/vnd.openxmlformats-officedocument.wordprocessingml.template`

Closes #1080: Corrected the mime type

---

docs/usage/setup.md

I might be being pedantic but I've added `disable_asserts` to table of global configuration options with a link to the Performance page.
I also added `case_sensitive` to confirm that this relates just to the adapter's file system. You can't, for example, pass a case insensitive directory name and expect Flysystem to return the correct case for a case sensitive adapter.

Added additional global configuration options

---

README.md

afaik it's called "AWS S3" or "Amazon S3", not "AwsS3". Also in the docs it's written like this.

consistent spelling of AWS S3

---

src/Adapter/Local.php

This PR is backward compatible. It simply nullifies `RecursiveIteratorIterator` to release directory lock and solve issue #1103.

Nullify iterator to release directory lock

---

src/Filesystem.php

PHP 7.4 doesn't allow array access on non-arrays any more. This problem was actually picked up by my Laravel Flysystem test suite: https://travis-ci.org/GrahamCampbell/Laravel-Flysystem/builds/622314799.

Fixed `get(...)` on PHP 7.4

---

src/Handler.php

The `$metadata` may be `false`, in which case, we should probably treat it as a `dir`, the same as what `get` in `Filesystem` does.

Fixed another PHP 7.4 bug

---

src/Adapter/AbstractFtpAdapter.php

The `normalizePermissions` method can receive permissions in their string format (ex. `-rw-r--r--`) but also in decimal format `33188`. This change will add support for the decimal format as previously it would be first truncated to 3188, which would then be interpreted as octal number and converted to decimal. After PHP 7.4, parsing a non-octal number with `octdec` will make PHP emit a Deprecation notice. 
Fixes: #1113

Fix deprecation message

---

src/Adapter/Ftp.php
src/ConnectionErrorException.php
src/ConnectionRuntimeException.php
src/Exception.php
src/FilesystemNotFoundException.php
src/FlysystemException.php
src/InvalidRootException.php
src/NotSupportedException.php
src/RootViolationException.php

The change will allow you to better capture particular exceptions and catch all the exceptions by iterface `FlysystemException ` (the main thing I needed).
This is not a BC break, as the new expetion inherits from the original. As evidenced by successful tests, see https://github.com/eddycek/flysystem/blob/refactoring-exception/tests/FtpTests.php#L446 and https://github.com/eddycek/flysystem/blob/refactoring-exception/tests/FtpTests.php#L794 etc.
The related PR has already been approved in `flysystem-sftp`, see https://github.com/thephpleague/flysystem-sftp/pull/86

Refactoring for capture exceptions 
